CREATE TABLE IF NOT EXISTS categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    CONSTRAINT uk_categoria_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    perfil VARCHAR(50) NOT NULL,
    ativo BOOLEAN DEFAULT TRUE,
    CONSTRAINT uk_usuario_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    preco NUMERIC(14, 2) NOT NULL,
    status VARCHAR(50),
    estoque INTEGER,
    version BIGINT,
    categoria_id BIGINT,
    data_criacao TIMESTAMP NOT NULL,
    data_modificacao TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS compras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    total NUMERIC(14, 2) NOT NULL,
    criada_em TIMESTAMP NOT NULL,
    demonstracao BOOLEAN,
    idempotency_key VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS itens_compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    nome_produto VARCHAR(255) NOT NULL,
    preco_unitario NUMERIC(14, 2) NOT NULL,
    quantidade INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS carrinho_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    CONSTRAINT uk_carrinho_usuario_produto UNIQUE (usuario_id, produto_id)
);

CREATE TABLE IF NOT EXISTS eventos_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange VARCHAR(255) NOT NULL,
    routing_key VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    publicado_em TIMESTAMP,
    tentativas INTEGER NOT NULL DEFAULT 0,
    ultimo_erro VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS categoria_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    nome VARCHAR(255),
    descricao VARCHAR(255),
    PRIMARY KEY (id, rev)
);

CREATE TABLE IF NOT EXISTS produto_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    nome VARCHAR(255),
    descricao VARCHAR(255),
    preco NUMERIC(14, 2),
    status VARCHAR(50),
    estoque INTEGER,
    version BIGINT,
    categoria_id BIGINT,
    data_criacao TIMESTAMP,
    data_modificacao TIMESTAMP,
    PRIMARY KEY (id, rev)
);

ALTER TABLE produto ADD COLUMN IF NOT EXISTS version BIGINT;
ALTER TABLE produto ALTER COLUMN preco SET DATA TYPE NUMERIC(14, 2);
ALTER TABLE compras ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(100);
ALTER TABLE compras ALTER COLUMN total SET DATA TYPE NUMERIC(14, 2);
ALTER TABLE itens_compra ALTER COLUMN preco_unitario SET DATA TYPE NUMERIC(14, 2);
ALTER TABLE eventos_outbox ADD COLUMN IF NOT EXISTS tentativas INTEGER DEFAULT 0;
UPDATE eventos_outbox SET tentativas = 0 WHERE tentativas IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_compra_usuario_idempotency
    ON compras (usuario_id, idempotency_key);
CREATE INDEX IF NOT EXISTS ix_eventos_outbox_pendentes
    ON eventos_outbox (publicado_em, id);
