apiVersion: v1
kind: ConfigMap
metadata:
  name: pb-at-config
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: antonio
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318/v1/traces
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "0.1"
  LOGGING_STRUCTURED_FORMAT_CONSOLE: ecs
  APP_DEMO_SEED: "true"
