apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pb-at

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - catalogo.yaml
  - avaliacoes.yaml
  - frontend.yaml
  - observability.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: pb-at
