apiVersion: v1
kind: Secret
metadata:
  name: pb-at-secrets
type: Opaque
stringData:
  POSTGRES_USER: antonio
  POSTGRES_PASSWORD: REPLACE_WITH_POSTGRES_PASSWORD
  SPRING_DATASOURCE_USERNAME: antonio
  SPRING_DATASOURCE_PASSWORD: REPLACE_WITH_POSTGRES_PASSWORD
  SPRING_RABBITMQ_PASSWORD: REPLACE_WITH_RABBITMQ_PASSWORD
  APP_AUTH_SECRET: REPLACE_WITH_LONG_RANDOM_AUTH_SECRET
  APP_INTERNAL_SECRET: REPLACE_WITH_LONG_RANDOM_INTERNAL_SECRET
