apiVersion: v1
kind: Secret
metadata:
  name: pb-at-secrets
type: Opaque
stringData:
  POSTGRES_USER: antonio
  POSTGRES_PASSWORD: admin123
  SPRING_DATASOURCE_USERNAME: antonio
  SPRING_DATASOURCE_PASSWORD: admin123
  SPRING_RABBITMQ_PASSWORD: admin123
  APP_AUTH_SECRET: pb-at-demo-secret-change-in-production
