CREATE TABLE IF NOT EXISTS compras_produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id BIGINT,
    usuario_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    demonstracao BOOLEAN NOT NULL DEFAULT FALSE,
    ativa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS produto_catalogo (
    id BIGINT PRIMARY KEY,
    nome VARCHAR(255),
    descricao VARCHAR(255),
    preco NUMERIC(14, 2),
    estoque INTEGER,
    status VARCHAR(50),
    categoria_id BIGINT,
    atualizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS avaliacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL,
    nome_usuario VARCHAR(255) NOT NULL,
    usuario_id BIGINT,
    nota INTEGER NOT NULL,
    comentario VARCHAR(1000),
    data_criacao TIMESTAMP NOT NULL,
    CONSTRAINT uk_avaliacao_usuario_produto UNIQUE (usuario_id, produto_id)
);

ALTER TABLE compras_produtos ADD COLUMN IF NOT EXISTS compra_id BIGINT;
ALTER TABLE compras_produtos ADD COLUMN IF NOT EXISTS ativa BOOLEAN DEFAULT TRUE;
UPDATE compras_produtos SET ativa = TRUE WHERE ativa IS NULL;
ALTER TABLE compras_produtos ALTER COLUMN ativa SET DEFAULT TRUE;
ALTER TABLE compras_produtos ALTER COLUMN ativa SET NOT NULL;
ALTER TABLE compras_produtos DROP CONSTRAINT IF EXISTS uk_compra_produto_usuario_produto;
CREATE UNIQUE INDEX IF NOT EXISTS uk_compra_produto_compra_produto
    ON compras_produtos (compra_id, produto_id);
